
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-courses-s24-4pm-2
owner: ucsb-cs156-s24
repo_name: proj-courses-s24-4pm-2
pull_requests: [{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-sameSection2","number":54,"title":"Kai same section2","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/54"},{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-betterUI2","number":53,"title":"km - fixed entertwining branches for better UI","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/53"},{"author":{"id":"MDQ6VXNlcjQ2NjU2NjI5","is_bot":false,"login":"kmflippo","name":""},"headRefName":"Kelly-delete-feature-with-swagger","number":52,"title":"Kelly delete feature with swagger ","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/52"},{"author":{"id":"U_kgDOBtTxaw","is_bot":false,"login":"evanja57","name":""},"headRefName":"EvanBuildingSearchBug","number":51,"title":"Evan-BUG: Fixing location history output order","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/51"},{"author":{"id":"U_kgDOBtTxaw","is_bot":false,"login":"evanja57","name":""},"headRefName":"EvanCourseOverTimeInstructorBug","number":49,"title":"Evan-BUG-Fixing Instructor search output order","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/49"},{"author":{"id":"U_kgDOCeK7pw","is_bot":false,"login":"WhrainySu","name":""},"headRefName":"Yusheng-Porject","number":35,"title":"BUG: Add course dialog allows adding course to the wrong schedule","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/35"},{"author":{"id":"U_kgDOBXuyIw","is_bot":false,"login":"kriteenshrestha","name":""},"headRefName":"ks-feature-course-search","number":30,"title":"kriteen - feature on the course history page (okay to type cs156 for course number) ","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/30"}]
