
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-courses-s24-4pm-2
owner: ucsb-cs156-s24
repo_name: proj-courses-s24-4pm-2
pull_requests: [{"author":{"id":"U_kgDOBtTxaw","is_bot":false,"login":"evanja57","name":""},"headRefName":"EvanGradeHistoryPage","number":47,"title":"Evan grade history page","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/47"},{"author":{"id":"MDQ6VXNlcjYwMzcwODQy","is_bot":false,"login":"jchanDev","name":"Julia Chan"},"headRefName":"julia-refactor-UI","number":46,"title":"Refactored Table UI with different colors","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/46"},{"author":{"id":"U_kgDOBtTxaw","is_bot":false,"login":"evanja57","name":""},"headRefName":"EvanGradeHistoryComponent","number":45,"title":"Evan grade history component","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/45"},{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-sameSection","number":43,"title":"Kai fixed bug on main search for add not showing up on certain lectures","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/43"},{"author":{"id":"U_kgDOCeK7pw","is_bot":false,"login":"WhrainySu","name":""},"headRefName":"Yusheng-Porject","number":35,"title":"BUG: Add course dialog allows adding course to the wrong schedule","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/35"},{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-sb3","number":32,"title":"Kai -updated spring boot to version 3","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/32"},{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-betterUI","number":31,"title":"Kai Better UI and UX in Main Course Search Page","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/31"},{"author":{"id":"U_kgDOBXuyIw","is_bot":false,"login":"kriteenshrestha","name":""},"headRefName":"ks-feature-course-search","number":30,"title":"kriteen - feature on the course history page (okay to type cs156 for course number) ","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/30"},{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-removeCourseRoute","number":28,"title":"Kai remove course route","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/28"},{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-BugsMainSearch","number":27,"title":"Kai - Fixed a Bug for the main search","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/27"}]
