
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-courses-s24-4pm-2
owner: ucsb-cs156-s24
repo_name: proj-courses-s24-4pm-2
pull_requests: [{"author":{"id":"U_kgDOBtTxaw","is_bot":false,"login":"evanja57","name":""},"headRefName":"Evan-CourseHistorySearchOutput","number":19,"title":"Evan course history search output correction","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/19"},{"author":{"id":"MDQ6VXNlcjYwMzcwODQy","is_bot":false,"login":"jchanDev","name":"Julia Chan"},"headRefName":"Julia-Add-Frontend_Job","number":18,"title":"Julia added frontend for UpdateGradeInfo in job","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/18"},{"author":{"id":"U_kgDOBXuyIw","is_bot":false,"login":"kriteenshrestha","name":""},"headRefName":"ks-feature-h2enable","number":17,"title":"Kriteen - h2enable feature","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/17"},{"author":{"id":"U_kgDOBXuyIw","is_bot":false,"login":"kriteenshrestha","name":""},"headRefName":"ks-feature-swaggeroption","number":15,"title":"ks - adding swagger option","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/15"}]
