
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-courses-s24-4pm-2
owner: ucsb-cs156-s24
repo_name: proj-courses-s24-4pm-2
pull_requests: [{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-removeCourseRoute","number":28,"title":"Kai remove course route","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/28"},{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-BugsMainSearch","number":27,"title":"Kai - Fixed a Bug for the main search","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/27"},{"author":{"id":"MDQ6VXNlcjQ2NjU2NjI5","is_bot":false,"login":"kmflippo","name":""},"headRefName":"Kelly-default-quarter","number":22,"title":"Kelly - Updating Default Quarter to be End Quarter","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/22"},{"author":{"id":"U_kgDOBtTxaw","is_bot":false,"login":"evanja57","name":""},"headRefName":"EvanGradeDistributionData","number":21,"title":"Evan - Adding fixture for data received from grade history api","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/21"},{"author":{"id":"U_kgDOBXuyIw","is_bot":false,"login":"kriteenshrestha","name":""},"headRefName":"ks-feature-h2enable","number":17,"title":"Kriteen - h2enable feature","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/17"}]
