
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-courses-s24-4pm-2
owner: ucsb-cs156-s24
repo_name: proj-courses-s24-4pm-2
pull_requests: [{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-sameSection2","number":54,"title":"Kai - add button not showing up for certain courses","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/54"},{"author":{"id":"U_kgDOBh_k6Q","is_bot":false,"login":"kai-maeda","name":""},"headRefName":"Kai-betterUI2","number":53,"title":"Kai- Added action column to add courses and show sections","url":"https://github.com/ucsb-cs156-s24/proj-courses-s24-4pm-2/pull/53"}]
